# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c873038cb7ac0039f1e0008e0004591cc5ee730c96b2fa4c6f2469c3b6ae5e209a631881459ad0e414c29f9d6622f6d5dd402d2adc616325b2c0bc3d3a1a06

test:
  secret_key_base: d385384db4a491e7607fa8ddbdd163d665850383b23c3d9faba0f917f2900c0474f80c18c0ca4afa0087c655a6b177e5dce9aa494d42107d77d7882ab1cdf4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
